### ISSUE TITLE
 Can not use keyword 'await' outside an async function (48:20)

### ISSUE THREAD

**Issue by tradingstratagem** [arkokoley/pdfvuer#51]
After upgrading to 1.5.0 I have the following compilation error:

ERROR in ./node_modules/pdfvuer/src/Pdfvuer.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/pdfvuer/src/Pdfvuer.vue?vue&type=script&lang=js&)
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: ./node_modules/pdfvuer/src/Pdfvuer.vue: Can not use keyword 'await' outside an async function (48:20)

**Comment by nicholaszuccarelli** [comment]
Yep, I'm getting the same problem too.

**Comment by arkokoley** [comment]
Fixed this in v1.5.1. Please upgrade to the latest version.
